# Generated by Django 4.1 on 2023-06-24 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterData', '0001_initial'),
        ('karyawan', '0001_initial'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rawat', models.CharField(blank=True, max_length=50, null=True)),
                ('no_registrasi', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_registrasi', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('jam_registrasi', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('penanggung_jawab_pasien', models.CharField(max_length=50)),
                ('status_periksa', models.CharField(choices=[('RALAN', 'RALAN'), ('RANAP', 'RANAP')], default='RALAN', max_length=50)),
                ('asuransi_pasien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.asuransi')),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pasien.pasien', to_field='no_rkm_medis')),
                ('poliklinik', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.poliklinik')),
            ],
            options={
                'verbose_name': 'Registrasi Pasien',
                'verbose_name_plural': 'Registrasi Pasien',
            },
        ),
    ]
