# Generated by Django 4.2 on 2023-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrasipasien',
            options={'verbose_name': 'Registrasi Pasien', 'verbose_name_plural': 'Registrasi Pasien'},
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='jam_registrasi',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='tgl_registrasi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
