# Generated by Django 4.2 on 2023-04-20 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0002_alter_registrasipasien_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasipasien',
            name='jam_registrasi',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='tgl_registrasi',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
