# Generated by Django 4.2 on 2023-04-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_alter_pasien_agama'),
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
        ('karyawan', '0004_alter_karyawan_agama'),
        ('frontOffice', '0003_alter_registrasipasien_jam_registrasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasipasien',
            name='asuransi_pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.asuransi'),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='dokter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan'),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pasien.pasien', to_field='no_rkm_medis'),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='poliklinik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.poliklinik'),
        ),
    ]
