# Generated by Django 4.2 on 2023-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0004_alter_registrasipasien_asuransi_pasien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasipasien',
            name='no_registrasi',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
