# Generated by Django 4.2 on 2023-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0005_alter_registrasipasien_no_registrasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasipasien',
            name='no_rawat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrasipasien',
            name='no_registrasi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
