# Generated by Django 4.2 on 2023-11-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0006_penyakit_prosedur'),
        ('pelayanan_medis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perawatan_rawat_jalan_pasien',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.kategori_perawatan'),
        ),
        migrations.DeleteModel(
            name='kategori_perawatan',
        ),
    ]
