# Generated by Django 4.2 on 2023-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan_medis', '0002_alter_perawatan_rawat_jalan_pasien_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perawatan_rawat_jalan_pasien',
            name='total_biaya',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
