# Generated by Django 4.2 on 2023-11-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan_medis', '0003_perawatan_rawat_jalan_pasien_total_biaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perawatan_rawat_jalan_pasien',
            name='nama_perawatan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
