# Generated by Django 4.2 on 2023-11-25 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0007_alter_absensikaryawan_jam_masuk_karyawan_and_more'),
        ('pelayanan_medis', '0004_alter_perawatan_rawat_jalan_pasien_nama_perawatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='perawatan_rawat_jalan_pasien',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dokter_pelaksana_tindakan_rj', to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan_pasien',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='petugas_pelaksana_tindakan_rj', to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan_pasien',
            name='tgl_perawatan',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
