# Generated by Django 4.2 on 2023-11-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan_medis', '0005_perawatan_rawat_jalan_pasien_dokter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perawatan_rawat_jalan_pasien',
            options={'verbose_name': 'Perawatan Rajal', 'verbose_name_plural': 'Perawatan Rajal'},
        ),
    ]
