# Generated by Django 4.2.2 on 2023-06-19 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterData', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_berkas', models.CharField(max_length=200)),
                ('berkas', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('keterangan_verifikator', models.TextField(blank=True, max_length=300, null=True)),
                ('status_berkas', models.CharField(choices=[('Berkas Diajukan', 'Berkas Diajukan'), ('Berkas Ditolak', 'Berkas Ditolak'), ('Berkas Diterima', 'Berkas Diterima')], default='Berkas Diajukan', max_length=50)),
            ],
            options={
                'verbose_name': 'Berkas Karyawan',
                'verbose_name_plural': 'Berkas Karyawan',
                'permissions': [('berkas_saya', 'Can access berkas saya')],
            },
        ),
        migrations.CreateModel(
            name='GolonganKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Golongan Karyawan',
                'verbose_name_plural': 'Golongan Karyawan',
            },
        ),
        migrations.CreateModel(
            name='JabatanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Jabatan Karyawan',
                'verbose_name_plural': 'Jabatan Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(8, 'must contain at least 8 characters')])),
                ('nik', models.CharField(blank=True, max_length=30, null=True)),
                ('nama', models.CharField(max_length=30)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('no_telfon', models.CharField(blank=True, max_length=30, null=True)),
                ('no_karyawan_tetap', models.CharField(blank=True, max_length=30, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_lahir', models.DateField(blank=True, max_length=30, null=True)),
                ('no_str', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_berlaku_str', models.DateField(blank=True, max_length=30, null=True)),
                ('no_sip', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_berlaku_sip', models.DateField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='karyawan/')),
                ('agama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.agama')),
                ('golongan_darah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.golongandarah')),
                ('golongan_karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.golongankaryawan')),
                ('jabatan_karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.jabatankaryawan')),
                ('jenis_kelamin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.jeniskelamin')),
            ],
            options={
                'verbose_name': 'Data Karyawan',
                'verbose_name_plural': 'Data Karyawan',
                'permissions': [('cv_saya', 'Can access cv saya'), ('dashboard_admin_karyawan', 'Can access dashboard admin karyawan'), ('dashboard_karyawan', 'Can access dashboard karyawan')],
            },
        ),
        migrations.CreateModel(
            name='KategoriBerkasKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Kategori Berkas',
                'verbose_name_plural': 'Kategori Berkas',
            },
        ),
        migrations.CreateModel(
            name='StatusKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Status Karyawan',
                'verbose_name_plural': 'Status Karyawan',
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=80)),
                ('tahun_lulus', models.CharField(max_length=10)),
                ('berkas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
                ('strata_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.stratapendidikan')),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Karyawan',
                'verbose_name_plural': 'Riwayat Pendidikan Karyawan',
                'permissions': [('riwayat_pendidikan_saya', 'Can access riwayat pendidikan saya')],
            },
        ),
        migrations.CreateModel(
            name='PelatihanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelatihan', models.CharField(max_length=200)),
                ('tanggal_pelatihan', models.DateField()),
                ('tahun_kegiatan', models.IntegerField()),
                ('tahun_expired', models.IntegerField(blank=True, null=True)),
                ('berkas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
            ],
            options={
                'verbose_name': 'Pelatihan Karyawan',
                'verbose_name_plural': 'Pelatihan Karyawan',
                'permissions': [('pelatihan_saya', 'Can access pelatihan saya')],
            },
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.statuskaryawan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_nikah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.statusnikah'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.unit'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KarirKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_menjabat', models.IntegerField()),
                ('tahun_berhenti_menjabat', models.IntegerField(blank=True, null=True)),
                ('berkas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.jabatankaryawan')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.unit')),
            ],
            options={
                'verbose_name': 'Karir Karyawan',
                'verbose_name_plural': 'Karir Karyawan',
                'permissions': [('karir_saya', 'Can access karir saya')],
            },
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.kategoriberkaskaryawan'),
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='verifikator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
