# Generated by Django 4.2 on 2023-04-18 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterData', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Status Karyawan',
                'verbose_name_plural': 'Status Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('agama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama')),
                ('golongan_darah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.golongandarah')),
                ('jenis_kelamin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.jeniskelamin')),
                ('status_karyawan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karyawan.statuskaryawan')),
                ('status_nikah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.statusnikah')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
            },
        ),
    ]
