# Generated by Django 4.1 on 2023-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jam_masuk', models.TimeField()),
                ('jam_pulang', models.TimeField()),
                ('keterangan', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Jam Kerja',
                'verbose_name_plural': 'Jam Kerja',
            },
        ),
    ]
