# Generated by Django 4.2 on 2023-06-11 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='kode',
            field=models.CharField(default='test', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(8, 'must contain at least 8 characters')]),
            preserve_default=False,
        ),
    ]
