# Generated by Django 4.1 on 2023-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_jamkerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamkerja',
            name='keterangan',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
