# Generated by Django 4.2 on 2023-06-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_alter_karyawan_kode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawan',
            options={'permissions': [('cv_saya', 'Can access cv saya')], 'verbose_name': 'Data Karyawan', 'verbose_name_plural': 'Data Karyawan'},
        ),
    ]
