# Generated by Django 4.2 on 2023-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='status_karyawan',
            field=models.ManyToManyField(to='karyawan.statuskaryawan'),
        ),
    ]
