# Generated by Django 4.2 on 2023-04-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0003_karyawan_status_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='status_karyawan',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='karyawan.statuskaryawan'),
        ),
    ]
