# Generated by Django 4.2 on 2023-04-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
        ('karyawan', '0003_alter_karyawan_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='agama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.agama'),
        ),
    ]
