# Generated by Django 4.1 on 2023-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0004_karyawan_jam_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamkerja',
            name='gunakan_aturan_jam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jamkerja',
            name='lama_jam_kerja',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
