# Generated by Django 4.2 on 2023-04-20 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
        ('karyawan', '0004_alter_karyawan_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='golongan_darah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.golongandarah'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jenis_kelamin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.jeniskelamin'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='status_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.statuskaryawan'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='status_nikah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.statusnikah'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
