# Generated by Django 4.2 on 2023-04-15 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karyawan', '0004_remove_karyawan_status_karyawan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
