# Generated by Django 4.2 on 2023-04-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0001_initial'),
        ('karyawan', '0005_alter_karyawan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='agama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='golongan_darah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.golongandarah'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='jenis_kelamin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.jeniskelamin'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_nikah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.statusnikah'),
        ),
    ]
