# Generated by Django 4.2 on 2023-05-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0005_alter_karyawan_golongan_darah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolonganKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Golongan Karyawan',
                'verbose_name_plural': 'Golongan Karyawan',
            },
        ),
        migrations.CreateModel(
            name='JabatanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Jabatan Karyawan',
                'verbose_name_plural': 'Jabatan Karyawan',
            },
        ),
        migrations.AddField(
            model_name='karyawan',
            name='golongan_karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.golongankaryawan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='jabatan_karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.jabatankaryawan'),
        ),
    ]
