# Generated by Django 4.1 on 2023-07-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0005_jamkerja_gunakan_aturan_jam_jamkerja_lama_jam_kerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_absen', models.DateField(blank=True, max_length=30, null=True)),
                ('jam_masuk_karyawan', models.TimeField()),
                ('jam_pulang_karyawan', models.TimeField()),
                ('lama_jam_kerja_karyawan', models.IntegerField(blank=True, null=True)),
                ('jam_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.jamkerja')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
            ],
            options={
                'verbose_name': 'Absensi Karyawan',
                'verbose_name_plural': 'Absensi Karyawan',
            },
        ),
    ]
