# Generated by Django 4.2 on 2023-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0006_golongankaryawan_jabatankaryawan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerkasKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Kategori Berkas Karyawan',
                'verbose_name_plural': 'Kategori Berkas Karyawan',
            },
        ),
    ]
