# Generated by Django 4.2 on 2023-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0007_kategoriberkaskaryawan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriberkaskaryawan',
            options={'verbose_name': 'Kategori Berkas', 'verbose_name_plural': 'Kategori Berkas'},
        ),
        migrations.AlterField(
            model_name='golongankaryawan',
            name='keterangan',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jabatankaryawan',
            name='keterangan',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
