# Generated by Django 4.2 on 2023-05-23 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karyawan', '0009_berkaskaryawan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkaskaryawan',
            options={'verbose_name': 'Berkas Karyawan', 'verbose_name_plural': 'Berkas Karyawan'},
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='keterangan_verifikator',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='berkaskaryawan',
            name='verifikator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
