# Generated by Django 4.2 on 2023-05-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0011_karyawan_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkaskaryawan',
            options={'permissions': [('verif_berkas', 'Can verif the status of berkas')], 'verbose_name': 'Berkas Karyawan', 'verbose_name_plural': 'Berkas Karyawan'},
        ),
    ]
