# Generated by Django 4.2 on 2023-05-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0012_alter_berkaskaryawan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkaskaryawan',
            name='status_berkas',
            field=models.CharField(choices=[('Berkas Diajukan', 'Berkas Diajukan'), ('Berkas Ditolak', 'Berkas Ditolak'), ('Berkas Diterima', 'Berkas Diterima')], default='Berkas Diajukan', max_length=50),
        ),
    ]
