# Generated by Django 4.2 on 2023-05-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0013_berkaskaryawan_status_berkas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkaskaryawan',
            options={'permissions': [('verif_berkas', 'Can verif the status of berkas'), ('view_all_berkas', 'Can view all berkas')], 'verbose_name': 'Berkas Karyawan', 'verbose_name_plural': 'Berkas Karyawan'},
        ),
    ]
