# Generated by Django 4.2 on 2023-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0015_karyawan_nik_karyawan_no_karyawan_tetap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkaskaryawan',
            options={'permissions': [('berkas_saya', 'Can access berkas saya')], 'verbose_name': 'Berkas Karyawan', 'verbose_name_plural': 'Berkas Karyawan'},
        ),
    ]
