# Generated by Django 4.2 on 2023-06-01 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0007_unit'),
        ('karyawan', '0016_alter_berkaskaryawan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPendidikanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=80)),
                ('tahun_lulus', models.CharField(max_length=10)),
                ('berkas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('strata_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.stratapendidikan')),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Karyawan',
                'verbose_name_plural': 'Riwayat Pendidikan Karyawan',
            },
        ),
    ]
