# Generated by Django 4.2 on 2023-06-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0007_unit'),
        ('karyawan', '0018_riwayatpendidikankaryawan_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarirKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_menjabat', models.CharField(max_length=10)),
                ('tahun_berhenti_menjabat', models.CharField(max_length=10)),
                ('berkas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='karyawan.jabatankaryawan')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.unit')),
            ],
            options={
                'verbose_name': 'Karir Karyawan',
                'verbose_name_plural': 'Karir Karyawan',
            },
        ),
    ]
