# Generated by Django 4.2 on 2023-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0019_karirkaryawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karirkaryawan',
            name='tahun_berhenti_menjabat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
