# Generated by Django 4.2 on 2023-06-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0020_alter_karirkaryawan_tahun_berhenti_menjabat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpendidikankaryawan',
            name='berkas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan'),
        ),
    ]
