# Generated by Django 4.2 on 2023-06-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0021_alter_riwayatpendidikankaryawan_berkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karirkaryawan',
            name='berkas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan'),
        ),
    ]
