# Generated by Django 4.2 on 2023-06-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0023_alter_karirkaryawan_tahun_berhenti_menjabat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawan',
            options={'verbose_name': 'Data Karyawan', 'verbose_name_plural': 'Data Karyawan'},
        ),
        migrations.AlterField(
            model_name='karirkaryawan',
            name='tahun_berhenti_menjabat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karirkaryawan',
            name='tahun_menjabat',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PelatihanKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelatihan', models.CharField(max_length=200)),
                ('tanggal_pelatihan', models.DateField()),
                ('tahun_kegiatan', models.IntegerField()),
                ('tahun_expired', models.IntegerField(blank=True, null=True)),
                ('berkas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.berkaskaryawan')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='karyawan.karyawan')),
            ],
            options={
                'verbose_name': 'Pelatihan Karyawan',
                'verbose_name_plural': 'Pelatihan Karyawan',
            },
        ),
    ]
