# Generated by Django 4.2 on 2023-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0024_alter_karyawan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='kode',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
