# Generated by Django 4.2 on 2023-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0026_karyawan_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='karyawan/'),
        ),
    ]
