# Generated by Django 4.2 on 2023-04-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecamatan',
            name='kota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.kota'),
        ),
        migrations.AlterField(
            model_name='kelurahan',
            name='kecamatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.kecamatan'),
        ),
        migrations.AlterField(
            model_name='kota',
            name='propinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.propinsi'),
        ),
        migrations.AlterField(
            model_name='propinsi',
            name='negara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.negara'),
        ),
    ]
