# Generated by Django 4.2 on 2023-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kecamatan',
            name='kode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kode_kota',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kode_provinsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kelurahan',
            name='kode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kelurahan',
            name='kode_kecamatan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kelurahan',
            name='kode_kota',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kelurahan',
            name='kode_provinsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kota',
            name='kode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kota',
            name='kode_provinsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propinsi',
            name='kode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
