# Generated by Django 4.2 on 2023-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0002_masternegara_kode_negara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('nicename', models.CharField(max_length=80)),
                ('iso3', models.CharField(max_length=10)),
                ('numcode', models.IntegerField()),
                ('phonecode', models.IntegerField()),
                ('kode_negara', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Negara',
                'verbose_name_plural': 'Negara',
            },
        ),
    ]
