# Generated by Django 4.2 on 2023-04-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0003_negara'),
    ]

    operations = [
        migrations.DeleteModel(
            name='masterNegara',
        ),
    ]
