# Generated by Django 4.2 on 2023-04-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0004_delete_masternegara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negara',
            name='kode_negara',
        ),
    ]
