# Generated by Django 4.2 on 2023-04-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0007_kota'),
    ]

    operations = [
        migrations.CreateModel(
            name='kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.AlterModelOptions(
            name='kota',
            options={'verbose_name': 'Kota', 'verbose_name_plural': 'Kota'},
        ),
        migrations.CreateModel(
            name='kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan',
                'verbose_name_plural': 'Kelurahan',
            },
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.kota'),
        ),
    ]
