# Generated by Django 4.2.2 on 2023-06-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Agama',
                'verbose_name_plural': 'Agama',
            },
        ),
        migrations.CreateModel(
            name='Asuransi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Asuransi',
                'verbose_name_plural': 'Asuransi',
            },
        ),
        migrations.CreateModel(
            name='Bangsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Bangsal',
                'verbose_name_plural': 'Bangsal',
            },
        ),
        migrations.CreateModel(
            name='GolonganDarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Golongan Darah',
                'verbose_name_plural': 'Golongan Darah',
            },
        ),
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Jenis Kelamin',
                'verbose_name_plural': 'Jenis Kelamin',
            },
        ),
        migrations.CreateModel(
            name='JenisPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Jenis Pekerjaan',
                'verbose_name_plural': 'Jenis Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='kategori_perawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Perawatan',
                'verbose_name_plural': 'Kategori Perawatan',
            },
        ),
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Poliklinik',
                'verbose_name_plural': 'Poliklinik',
            },
        ),
        migrations.CreateModel(
            name='StatusNikah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Status Nikah',
                'verbose_name_plural': 'Status Nikah',
            },
        ),
        migrations.CreateModel(
            name='StrataPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Strata Pendidikan',
                'verbose_name_plural': 'Strata Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='perawatan_rawat_jalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama_perawatan', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.kategori_perawatan')),
            ],
            options={
                'verbose_name': 'Perawatan Rawat Jalan',
                'verbose_name_plural': 'Perawatan Rawat Jalan',
            },
        ),
    ]
