# Generated by Django 4.2 on 2023-04-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
