# Generated by Django 4.1 on 2023-06-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
    ]
