# Generated by Django 4.2 on 2023-04-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asuransi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Asuransi',
                'verbose_name_plural': 'Asuransi',
            },
        ),
    ]
