# Generated by Django 4.2 on 2023-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0002_poliklinik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Bangsal',
                'verbose_name_plural': 'Bangsal',
            },
        ),
        migrations.AlterModelOptions(
            name='poliklinik',
            options={'verbose_name': 'Poliklinik', 'verbose_name_plural': 'Poliklinik'},
        ),
    ]
