# Generated by Django 4.2 on 2023-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategori_perawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Kategori Perawatan',
                'verbose_name_plural': 'Kategori Perawatan',
            },
        ),
    ]
