# Generated by Django 4.2 on 2023-11-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0003_ruangan_ruanganunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_material',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perawatan_rawat_jalan',
            name='kategori',
            field=models.ForeignKey(blank=True, help_text='Kategori perawatan dokter / perawat', null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.kategori_perawatan'),
        ),
        migrations.AlterField(
            model_name='perawatan_rawat_jalan',
            name='status',
            field=models.BooleanField(help_text='status aktif tindakan'),
        ),
    ]
