# Generated by Django 4.2 on 2023-04-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0004_kategori_perawatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='perawatan_rawat_jalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama_perawatan', models.CharField(max_length=50)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.kategori_perawatan')),
            ],
            options={
                'verbose_name': 'Perawatan Rawat Jalan',
                'verbose_name_plural': 'Perawatan Rawat Jalan',
            },
        ),
    ]
