# Generated by Django 4.2 on 2023-11-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0004_perawatan_rawat_jalan_biaya_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_bhp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_dokter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_kso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_manajemen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_perawat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='biaya_rawat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perawatan_rawat_jalan',
            name='biaya_material',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
