# Generated by Django 4.2 on 2023-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0005_perawatan_rawat_jalan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori_perawatan',
            name='status',
        ),
        migrations.AddField(
            model_name='perawatan_rawat_jalan',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
