# Generated by Django 4.2 on 2023-04-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rkm_medis', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField()),
                ('agama', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama')),
                ('golongan_darah', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.golongandarah')),
                ('jenis_kelamin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.jeniskelamin')),
            ],
        ),
    ]
