# Generated by Django 4.2 on 2023-04-15 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0008_kecamatan_alter_kota_options_kelurahan_and_more'),
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasien',
            options={'verbose_name': 'Data Pasien', 'verbose_name_plural': 'Data Pasien'},
        ),
        migrations.AddField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.negara'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='propinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.propinsi'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama'),
        ),
    ]
