# Generated by Django 4.2 on 2023-04-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.agama'),
        ),
    ]
