# Generated by Django 4.2 on 2023-04-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0002_alter_kecamatan_kota_alter_kelurahan_kecamatan_and_more'),
        ('masterData', '0003_bangsal_alter_poliklinik_options'),
        ('pasien', '0002_alter_pasien_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='golongan_darah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.golongandarah'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterData.jeniskelamin'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.jenispekerjaan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.kecamatan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.kelurahan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.kota'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.negara'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='propinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterWilayah.propinsi'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_nikah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.statusnikah'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='strata_pendidikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.stratapendidikan'),
        ),
    ]
