# Generated by Django 4.2 on 2023-04-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
        ('pasien', '0003_remove_pasien_propinsi_alter_pasien_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama'),
        ),
    ]
