# Generated by Django 4.2 on 2023-04-15 23:41
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0004_alter_pasien_agama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='propinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.propinsi')
        ),
    ]
