# Generated by Django 4.2 on 2023-04-15 23:52
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0007_alter_pasien_propinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.negara')
        ),
    ]
