# Generated by Django 4.2 on 2023-04-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
        ('masterWilayah', '0008_kecamatan_alter_kota_options_kelurahan_and_more'),
        ('pasien', '0008_alter_pasien_negara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='propinsi',
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.negara'),
        ),
    ]
