# Generated by Django 4.2 on 2023-04-16 12:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0008_kecamatan_alter_kota_options_kelurahan_and_more'),
        ('pasien', '0011_remove_pasien_propinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='propinsi',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='negara', chained_model_field='negara', null=True, on_delete=django.db.models.deletion.CASCADE, to='masterWilayah.propinsi'),
        ),
    ]
