# Generated by Django 4.2 on 2023-04-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0012_pasien_propinsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='propinsi',
        ),
    ]
