# Generated by Django 4.2 on 2023-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0015_pasien_kecamatan_pasien_kelurahan_pasien_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='no_rkm_medis',
            field=models.CharField(default='B1F00', editable=False, max_length=50),
        ),
    ]
