# Generated by Django 4.2 on 2023-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0016_alter_pasien_no_rkm_medis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='no_rkm_medis',
            field=models.CharField(default='4258C', editable=False, max_length=50, unique=True),
        ),
    ]
