# Generated by Django 4.2 on 2023-04-16 21:49

from django.db import migrations, models
import django.db.models.deletion
import pasien.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterData', '0002_jenispekerjaan_stratapendidikan'),
        ('masterWilayah', '0008_kecamatan_alter_kota_options_kelurahan_and_more'),
        ('pasien', '0018_alter_pasien_no_rkm_medis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='jenis_pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.jenispekerjaan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='no_ktp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='no_telfon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='status_nikah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.statusnikah'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='strata_pendidikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.stratapendidikan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tgl_daftar',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.agama'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='golongan_darah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterData.golongandarah'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.kecamatan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.kelurahan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.kota'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.negara'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='no_rkm_medis',
            field=models.CharField(blank=True, default=pasien.models.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='propinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.propinsi'),
        ),
    ]
