# Generated by Django 4.2 on 2023-04-16 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0019_pasien_jenis_pekerjaan_pasien_no_ktp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tgl_daftar',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
