# Generated by Django 4.2 on 2023-04-16 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWilayah', '0008_kecamatan_alter_kota_options_kelurahan_and_more'),
        ('pasien', '0020_alter_pasien_nip_alter_pasien_tgl_daftar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='negara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterWilayah.negara'),
        ),
    ]
