# Generated by Django 4.2 on 2023-11-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterData', '0007_perawatan_rawat_jalan_total_biaya'),
        ('frontoffice', '0002_remove_registrasi_jam_registrasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Primary', 'Primary'), ('Sekunder', 'Sekunder')], default='Primary', max_length=50)),
                ('diagnosa_dokter', models.TextField(blank=True, max_length=300, null=True)),
                ('diagnosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterData.penyakit')),
                ('no_rawat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='frontoffice.registrasi')),
            ],
            options={
                'verbose_name': 'Diagnosa (ICD 10)',
                'verbose_name_plural': 'Diagnosa (ICD 10)',
            },
        ),
    ]
