# Generated by Django 4.2 on 2023-11-26 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0007_alter_absensikaryawan_jam_masuk_karyawan_and_more'),
        ('rekamMedis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_diagnosa', to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='dokter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dokter_pemberi_diagnosa', to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='status_periksa',
            field=models.CharField(choices=[('RALAN', 'RALAN'), ('RANAP', 'RANAP')], default='RALAN', max_length=50),
        ),
    ]
